

services:

  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile.laravel
    working_dir: /var/www/html/laravel 
    ports:
      - 5001:80
    volumes:
      - ./laravel:/var/www/html/laravel
      - ./src:/var/www/html/src

  app:
    build:
      context: ./web
      dockerfile: Dockerfile.laravel
    container_name: laravel_app
    ports:
      - "3001:80"   # Alterei a porta 80 do container para 8080 no host
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: always
    ports:
      - "4001:4002"   # Alterei a porta do MySQL (host:container)
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin
    restart: always
    ports:
      - "7070:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db

volumes:
  db_data:
