

services:

  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile.laravel
    working_dir: /var/www/html/laravel 
    ports:
      - 5001:80
    volumes:
      - ./laravel:/var/www/html/laravel

  db:
    image: mysql:8 # imagem do docker hub escolhida
    platform: linux/x86_64 # SO escolhido para o banco
    restart: unless-stopped # serviço sempre reiniciado
    container_name: db # nome do serviço
    environment:
        MYSQL_DATABASE: reciclabits
        MYSQL_ROOT_PASSWORD: root
        MYSQL_PASSWORD: root
        MYSQL_USER: t99
    volumes: # pastas espelhadas no container
        - mysql:/var/lib/mysql
    ports: # portas de acesso
        - "4001:3306"


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "7070:80"
    environment:
      PMA_HOST: db
      PMA_user: root
      PMA_PASSWORD: root
    depends_on:
      - db

volumes:
  mysql:
