FROM php:8.2-apache

# Instala extensões necessárias para o Laravel
RUN docker-php-ext-install pdo pdo_mysql

# Ativa mod_rewrite para o Apache
RUN a2enmod rewrite

# Configura o DocumentRoot do Laravel
WORKDIR /var/www/html

# Copia os arquivos (se não estiver usando volume)
# COPY ../src/ /var/www/html/

# Dá permissão para o storage e bootstrap/cache
RUN chown -R www-data:www-data /var/www/html \
    && chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache
